# Site settings
title: Consulting Recherches Privées
logo: logo_aigle.png
background: aigle.jpg
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
author: Copyright &copy; 2019 - Start Bootstrap
lang: fr

# Build settings
safe: true # always trues on github-pages, disables _plugins/
assets:
  cache: false
markdown: kramdown
sass:
  indentWidth: 4
  style: compressed
  precision: 10
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
  - build-in-docker.sh
  - README.md
  - vendor
